### ISSUE TITLE
Bit of code works great until I integrate it into my existing program

### ISSUE THREAD

**Issue by gjanosz** [StevePaget/Pygame_Functions#5]
This code works fine in isolation:
***************************************************************
from pygame_functions import *
screenSize(500, 500)
setBackgroundColour("red")
#instructionLabel = makeLabel("Please enter a word", 40, 10, 40, ("blue"), "AZgency FB", 'yellow')
#showLabel(instructionLabel)
wordBox1 = makeTextBox(10, 80, 300, 0, "Enter distance to ball:", 0, 24)
showTextBox(wordBox1)
entry1 = textBoxInput(wordBox1)
wordlabel = makeLabel(entry1, 30, 10, 120, "black")
showLabel(wordlabel)
hyp = int(entry1)
hideTextBox(wordBox1)
wordBox2 = makeTextBox(10, 80, 300, 0, "Enter number of degrees:", 0, 24)
showTextBox(wordBox2)
entry2 = textBoxInput(wordBox2)
wordlabel2 = makeLabel(entry2, 30, 10, 150, "black")
showLabel(wordlabel2)
deg = int(entry2)
hideTextBox(wordBox2)
endWait()
****************************************************
But I get the following error messages when integrated into my existing program:
Traceback (most recent call last):
  File "C:\Users\gjano\learnEXP1.py", line 483, in <module>
    measure()
  File "C:\Users\gjano\learnEXP1.py", line 226, in measure
    showTextBox(wordBox1)
  File "C:\Users\gjano\pygame_functions.py", line 572, in showTextBox
    updateDisplay()
  File "C:\Users\gjano\pygame_functions.py", line 582, in updateDisplay
    spriteRects = spriteGroup.draw(screen)
  File "C:\Users\gjano\AppData\Roaming\Python\Python36\site-packages\pygame\sprite.py", line 568, in draw
    surface_blit = surface.blit
AttributeError: 'str' object has no attribute 'blit'
